In [118]:
import matplotlib as notebook
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from pandas.io.json import json_normalize
import json
from pprint import pprint
import requests

### New York Income by county

In [119]:
# Income Tax Components by Size of Income by Place of Residence: Beginning Tax Year 1999
# Website https://catalog.data.gov/dataset/income-tax-components-by-size-of-income-by-place-of-residence-beginning-tax-year-1999

income_file = "Income_Tax_Components_by_Size_of_Income_by_Place_of_Residence__Beginning_Tax_Year_1999.csv"
income_df = pd.read_csv(income_file)
income_df.head(5)

,Tax Year,Resident Type,Place of Residence,Country,State,County,Income Class,Disclosure,Number of All Returns,NY AGI of All Returns (in thousands) *,Deductions of All Returns (in thousands),Dependent Exemptions of All Returns (in thousands),Taxable Income of All Returns (in thousands),Tax Before Credits of All Returns (in thousands),Tax Liability of All Returns (in thousands) **,Place of Residence Sort Order,Income Class Sort Order
0,2014,Full-Year Resident,New York City - Bronx,United States,New York,New York City - Bronx,"Under 5,000",NaN,115872.0,28535.0,121985.0,1.0,3336.0,134.0,-7226.0,1,1
1,2014,Full-Year Resident,New York City - Bronx,United States,New York,New York City - Bronx,"5,000 - 9,999",NaN,64472.0,497520.0,453287.0,3908.0,40326.0,1614.0,-24641.0,1,2
2,2014,Full-Year Resident,New York City - Bronx,United States,New York,New York City - Bronx,"10,000 - 19,999",NaN,125775.0,1848243.0,1222947.0,87665.0,537631.0,21718.0,-83446.0,1,3
3,2014,Full-Year Resident,New York City - Bronx,United States,New York,New York City - Bronx,"20,000 - 29,999",NaN,82181.0,2028682.0,867454.0,73712.0,1087516.0,47154.0,-11813.0,1,4
4,2014,Full-Year Resident,New York City - Bronx,United States,New York,New York City - Bronx,"30,000 - 39,999",NaN,64824.0,2259144.0,713694.0,58814.0,1486635.0,70581.0,38911.0,1,5

In [120]:
# Creating a new column Total Returns by multiplying the columns Number of all returns and NY average gross income(AGI) to 
income_df['Total Returns'] = income_df['Number of All Returns'] * income_df['NY AGI of All Returns (in thousands) *']
income_df.head(2)

,Tax Year,Resident Type,Place of Residence,Country,State,County,Income Class,Disclosure,Number of All Returns,NY AGI of All Returns (in thousands) *,Deductions of All Returns (in thousands),Dependent Exemptions of All Returns (in thousands),Taxable Income of All Returns (in thousands),Tax Before Credits of All Returns (in thousands),Tax Liability of All Returns (in thousands) **,Place of Residence Sort Order,Income Class Sort Order,Total Returns
0,2014,Full-Year Resident,New York City - Bronx,United States,New York,New York City - Bronx,"Under 5,000",NaN,115872.0,28535.0,121985.0,1.0,3336.0,134.0,-7226.0,1,1,3.306408e+09
1,2014,Full-Year Resident,New York City - Bronx,United States,New York,New York City - Bronx,"5,000 - 9,999",NaN,64472.0,497520.0,453287.0,3908.0,40326.0,1614.0,-24641.0,1,2,3.207611e+10

In [121]:
county_income_df = income_df.groupby('County').agg({"Total Returns": "sum", "Number of All Returns": "sum"})
county_income_df["Average Income"] = round(county_income_df["Total Returns"] / county_income_df["Number of All Returns"])
county_income_df.reset_index(inplace=True)
county_income_df.head(2)

   County  Total Returns  Number of All Returns  Average Income
0  Albany   1.662376e+13              4419684.0       3761300.0
1     All   5.176705e+14             21648618.0      23912402.0

### Community Health Obesity and Diabetes Related Indicators

In [122]:
# Community Health Obesity and Diabetes Related Indicators: 2008 - 2012
# Website https://health.data.ny.gov/Health/Community-Health-Obesity-and-Diabetes-Related-Indi/tchg-ruva
# API: https://health.data.ny.gov/resource/qtc8-nfcv.json    

url = "https://health.data.ny.gov/resource/qtc8-nfcv.json"
data = requests.get(url).json()
health_df = pd.DataFrame.from_dict(data)
#health_df.to_csv('qtc8-nfcv.csv')
health_df.head(2)

,:@computed_region_43an_4dx5,:@computed_region_9yqb_tdyd,_95_ci,county_code,county_name,data_comments,data_sources,data_years,denominator,denominator_note,indicator,indicator_number,location,mapping_distribution,measure_unit,percentage_rate,quartile,region_name,total_event_counts
0,NaN,NaN,NaN,101,Western New York,NaN,2009-2011 Vital Statistics Data as of February...,2009-2011,1537947,Average annual population,"Cardiovascular disease mortality rate per 100,000",d1,NaN,NaN,Rate,363.8,NaN,Western New York,16787
1,NaN,NaN,NaN,102,Finger Lakes,NaN,2009-2011 Vital Statistics Data as of February...,2009-2011,1271131,Average annual population,"Cardiovascular disease mortality rate per 100,000",d1,NaN,NaN,Rate,273.7,NaN,Finger Lakes,10438

In [123]:
# Clean and remove unwanted columns
health_df = health_df.drop(columns=[':@computed_region_43an_4dx5', ':@computed_region_9yqb_tdyd', '_95_ci', 
                                    'county_code', 'data_comments', 'location', 'mapping_distribution'])
health_df.head(2)

,county_name,data_sources,data_years,denominator,denominator_note,indicator,indicator_number,measure_unit,percentage_rate,quartile,region_name,total_event_counts
0,Western New York,2009-2011 Vital Statistics Data as of February...,2009-2011,1537947,Average annual population,"Cardiovascular disease mortality rate per 100,000",d1,Rate,363.8,NaN,Western New York,16787
1,Finger Lakes,2009-2011 Vital Statistics Data as of February...,2009-2011,1271131,Average annual population,"Cardiovascular disease mortality rate per 100,000",d1,Rate,273.7,NaN,Finger Lakes,10438

### Combine both data

In [124]:
#rename county name to match for merge
county_income_df = county_income_df.rename(columns={'County': 'county_name', 'Average Income': 'average_income'})

# Set county_name as index in both tables.
county_income_df = county_income_df.set_index('county_name')
health_df = health_df.set_index('county_name')

In [125]:
health_df.head(2)

,data_sources,data_years,denominator,denominator_note,indicator,indicator_number,measure_unit,percentage_rate,quartile,region_name,total_event_counts
county_name,,,,,,,,,,,
Western New York,2009-2011 Vital Statistics Data as of February...,2009-2011,1537947,Average annual population,"Cardiovascular disease mortality rate per 100,000",d1,Rate,363.8,NaN,Western New York,16787
Finger Lakes,2009-2011 Vital Statistics Data as of February...,2009-2011,1271131,Average annual population,"Cardiovascular disease mortality rate per 100,000",d1,Rate,273.7,NaN,Finger Lakes,10438

In [126]:
county_income_df.head(2)

             Total Returns  Number of All Returns  average_income
county_name
Albany        1.662376e+13              4419684.0       3761300.0
All           5.176705e+14             21648618.0      23912402.0

In [127]:
# Merge tables and only pick data at county level. First table as additional non county data that is no required.
health_df = pd.merge(health_df,
                 county_income_df[['average_income']],
                 on='county_name')
health_df.head(100)

,data_sources,data_years,denominator,denominator_note,indicator,indicator_number,measure_unit,percentage_rate,quartile,region_name,total_event_counts,average_income
county_name,,,,,,,,,,,,
Queens,2009-2011 Vital Statistics Data as of February...,2009-2011,2261761,Average annual population,"Cardiovascular disease mortality rate per 100,000",d1,Rate,268.8,0 - < 296.3 : Q1 & Q2,New York City,18237,19090523.0
Queens,2009-2011 NYS Pediatric Nutrition Surveillance...,2009-2011,26882,Average annual population,Percentage obese (95th percentile or higher) c...,g72,Percentage,15.5,15.1 - < 16.0 : Q3,New York City,12500,19090523.0
Queens,2009-2011 NYS Pediatric Nutrition Surveillance...,2009-2011,29963,Average annual population,Percentage of children (aged 2-4 years) enroll...,g73,Percentage,85.8,80.7 + : Q3 & Q4,New York City,77126,19090523.0
Queens,2008-2009 NYS Expanded Behavioral Risk Factor ...,2008-2009,NaN,NaN,Age-adjusted percentage of adults overweight o...,g74,Percentage,56.4,0 - < 62.9 : Q1 & Q2,New York City,NaN,19090523.0
Queens,2008-2009 NYS Expanded Behavioral Risk Factor ...,2008-2009,NaN,NaN,Age-adjusted percentage of adults obese (BMI 3...,g75,Percentage,20.6,0 - < 27.6 : Q1 & Q2,New York City,NaN,19090523.0
Queens,2008-2009 NYS Expanded Behavioral Risk Factor ...,2008-2009,NaN,NaN,Age-adjusted percentage of adults who did not ...,g76,Percentage,71.9,0 - < 78.2 : Q1 & Q2,New York City,NaN,19090523.0
Richmond,2009-2011 Vital Statistics Data as of February...,2009-2011,476976,Average annual population,"Diabetes mortality rate per 100,000",d22,Rate,22.3,20.4 - < 26.5 : Q3,New York City,319,5548961.0
Richmond,2009-2011 NYS Pediatric Nutrition Surveillance...,2009-2011,3316,Average annual population,Percentage obese (95th percentile or higher) c...,g72,Percentage,16.9,16.0 + : Q4,New York City,1681,5548961.0
Richmond,2009-2011 NYS Pediatric Nutrition Surveillance...,2009-2011,3698,Average annual population,Percentage of children (aged 2-4 years) enroll...,g73,Percentage,61.6,0.0 - < 75.2 : Q1,New York City,6834,5548961.0
Richmond,2008-2009 NYS Expanded Behavioral Risk Factor ...,2008-2009,NaN,NaN,Age-adjusted percentage of adults overweight o...,g74,Percentage,64.9,62.9 - < 66.3 : Q3,New York City,NaN,5548961.0
Richmond,2008-2009 NYS Expanded Behavioral Risk Factor ...,2008-2009,NaN,NaN,Age-adjusted percentage of adults obese (BMI 3...,g75,Percentage,26.6,0 - < 27.6 : Q1 & Q2,New York City,NaN,5548961.0
Richmond,2008-2009 NYS Expanded Behavioral Risk Factor ...,2008-2009,NaN,NaN,Age-adjusted percentage of adults who did not ...,g76,Percentage,70.2,0 - < 78.2 : Q1 & Q2,New York City,NaN,5548961.0
Ulster,2009-2011 Vital Statistics Data as of February...,2009-2011,182127,Average annual population,"Diabetes mortality rate per 100,000",d22,Rate,20.3,0 - < 20.4 : Q1 & Q2,Hudson Valley,111,1924215.0
Ulster,2009-2011 Vital Statistics Data as of February...,2009-2011,182127,Average annual population,"Cardiovascular disease mortality rate per 100,000",d1,Rate,278.2,0 - < 296.3 : Q1 & Q2,Hudson Valley,1520,1924215.0
Ulster,2010-2012 Student Weight Status Category Repor...,2010-2012,NaN,NaN,Percentage obese (95th percentile or higher) -...,g64,Percentage,18.8,0 - < 18.9 : Q1 & Q2,Hudson Valley,NaN,1924215.0
Ulster,2010-2012 Student Weight Status Category Repor...,2010-2012,NaN,NaN,Percentage overweight or obese (85th percentil...,g65,Percentage,36.2,35.4 - < 37.8 : Q3,Hudson Valley,NaN,1924215.0
Ulster,2010-2012 Student Weight Status Category Repor...,2010-2012,NaN,NaN,Percentage overweight but not obese (85th-<95t...,g66,Percentage,18.3,17.2 + : Q4,Hudson Valley,NaN,1924215.0
Ulster,2010-2012 Student Weight Status Category Repor...,2010-2012,NaN,NaN,Percentage obese (95th percentile or higher ) ...,g67,Percentage,18.5,18.0 - < 19.4 : Q3,Hudson Valley,NaN,1924215.0
Ulster,2010-2012 Student Weight Status Category Repor...,2010-2012,NaN,NaN,Percentage overweight or obese (85th percentil...,g68,Percentage,36.8,36.5 + : Q4,Hudson Valley,NaN,1924215.0
Ulster,2010-2012 Student Weight Status Category Repor...,2010-2012,NaN,NaN,Percentage overweight but not obese (85th-<95t...,g69,Percentage,16.7,0 - < 16.9 : Q1 & Q2,Hudson Valley,NaN,1924215.0
Ulster,2010-2012 Student Weight Status Category Repor...,2010-2012,NaN,NaN,Percentage obese (95th percentile or higher ) ...,g70,Percentage,20.4,0 - < 21.1 : Q1 & Q2,Hudson Valley,NaN,1924215.0
Ulster,2010-2012 Student Weight Status Category Repor...,2010-2012,NaN,NaN,Percentage overweight or obese (85th percentil...,g71,Percentage,37.2,0 - < 37.5 : Q1 & Q2,Hudson Valley,NaN,1924215.0
Ulster,2009-2011 NYS Pediatric Nutrition Surveillance...,2009-2011,785,Average annual population,Percentage obese (95th percentile or higher) c...,g72,Percentage,17.5,16.0 + : Q4,Hudson Valley,412,1924215.0
Ulster,2009-2011 NYS Pediatric Nutrition Surveillance...,2009-2011,860,Average annual population,Percentage of children (aged 2-4 years) enroll...,g73,Percentage,78.8,75.2 - < 80.7 : Q2,Hudson Valley,2033,1924215.0
Ulster,2008-2009 NYS Expanded Behavioral Risk Factor ...,2008-2009,NaN,NaN,Age-adjusted percentage of adults overweight o...,g74,Percentage,59.6,0 - < 62.9 : Q1 & Q2,Hudson Valley,NaN,1924215.0
Ulster,2008-2009 NYS Expanded Behavioral Risk Factor ...,2008-2009,NaN,NaN,Age-adjusted percentage of adults obese (BMI 3...,g75,Percentage,24.9,0 - < 27.6 : Q1 & Q2,Hudson Valley,NaN,1924215.0
Ulster,2008-2009 NYS Expanded Behavioral Risk Factor ...,2008-2009,NaN,NaN,Age-adjusted percentage of adults who did not ...,g76,Percentage,75.4,0 - < 78.2 : Q1 & Q2,Hudson Valley,NaN,1924215.0
Ulster,2008-2009 NYS Expanded Behavioral Risk Factor ...,2008-2009,NaN,NaN,Age-adjusted percentage of adults eating 5 or ...,g77,Percentage,29.3,26.0 + : Q3 & Q4,Hudson Valley,NaN,1924215.0
Montgomery,2009-2011 Vital Statistics Data as of February...,2009-2011,49584,Average annual population,"Age-adjusted cirrhosis mortality rate per 100,000",d21a,Rate,9.5,9.0 + : Q4,Northeastern New York,16,424399.0
Montgomery,2010-2012 Student Weight Status Category Repor...,2010-2012,NaN,NaN,Percentage obese (95th percentile or higher) -...,g64,Percentage,13.5,0 - < 18.9 : Q1 & Q2,Northeastern New York,NaN,424399.0
...,...,...,...,...,...,...,...,...,...,...,...,...
Albany,2008-2009 NYS Expanded Behavioral Risk Factor ...,2008-2009,NaN,NaN,Age-adjusted percentage of adults eating 5 or ...,g77,Percentage,23.9,0.0 - < 24.0 : Q1,Northeastern New York,NaN,3761300.0
Clinton,2010-2012 Student Weight Status Category Repor...,2010-2012,NaN,NaN,Percentage obese (95th percentile or higher) -...,g64,Percentage,20.6,20.4 + : Q4,Northeastern New York,NaN,708227.0
Clinton,2010-2012 Student Weight Status Category Repor...,2010-2012,NaN,NaN,Percentage overweight or obese (85th percentil...,g65,Percentage,39.0,37.8 + : Q4,Northeastern New York,NaN,708227.0
Clinton,2010-2012 Student Weight Status Category Repor...,2010-2012,NaN,NaN,Percentage overweight but not obese (85th-<95t...,g66,Percentage,18.1,17.2 + : Q4,Northeastern New York,NaN,708227.0
Clinton,2010-2012 Student Weight Status Category Repor...,2010-2012,NaN,NaN,Percentage obese (95th percentile or higher ) ...,g67,Percentage,19.1,18.0 - < 19.4 : Q3,Northeastern New York,NaN,708227.0
Clinton,2010-2012 Student Weight Status Category Repor...,2010-2012,NaN,NaN,Percentage overweight or obese (85th percentil...,g68,Percentage,37.3,36.5 + : Q4,Northeastern New York,NaN,708227.0
Clinton,2010-2012 Student Weight Status Category Repor...,2010-2012,NaN,NaN,Percentage overweight but not obese (85th-<95t...,g69,Percentage,19.2,18.9 + : Q4,Northeastern New York,NaN,708227.0
Clinton,2010-2012 Student Weight Status Category Repor...,2010-2012,NaN,NaN,Percentage obese (95th percentile or higher ) ...,g70,Percentage,22.3,21.1 - < 22.5 : Q3,Northeastern New York,NaN,708227.0
Clinton,2010-2012 Student Weight Status Category Repor...,2010-2012,NaN,NaN,Percentage overweight or obese (85th percentil...,g71,Percentage,41.5,40.1 + : Q4,Northeastern New York,NaN,708227.0
Clinton,2009-2011 NYS Pediatric Nutrition Surveillance...,2009-2011,851,Average annual population,Percentage obese (95th percentile or higher) c...,g72,Percentage,15.3,15.1 - < 16.0 : Q3,Northeastern New York,391,708227.0
Clinton,2009-2011 NYS Pediatric Nutrition Surveillance...,2009-2011,918,Average annual population,Percentage of children (aged 2-4 years) enroll...,g73,Percentage,82.6,80.7 + : Q3 & Q4,Northeastern New York,2276,708227.0
Clinton,2008-2009 NYS Expanded Behavioral Risk Factor ...,2008-2009,NaN,NaN,Age-adjusted percentage of adults overweight o...,g74,Percentage,71.0,66.3 + : Q4,Northeastern New York,NaN,708227.0
Clinton,2008-2009 NYS Expanded Behavioral Risk Factor ...,2008-2009,NaN,NaN,Age-adjusted percentage of adults obese (BMI 3...,g75,Percentage,33.0,29.8 + : Q4,Northeastern New York,NaN,708227.0
Clinton,2008-2009 NYS Expanded Behavioral Risk Factor ...,2008-2009,NaN,NaN,Age-adjusted percentage of adults who did not ...,g76,Percentage,79.4,78.2 - < 80.7 : Q3,Northeastern New York,NaN,708227.0
Clinton,2008-2009 NYS Expanded Behavioral Risk Factor ...,2008-2009,NaN,NaN,Age-adjusted percentage of adults eating 5 or ...,g77,Percentage,27.2,26.0 + : Q3 & Q4,Northeastern New York,NaN,708227.0
Columbia,2010-2012 Student Weight Status Category Repor...,2010-2012,NaN,NaN,Percentage obese (95th percentile or higher) -...,g64,Percentage,19.1,18.9 - < 20.4 : Q3,Northeastern New York,NaN,700463.0
Columbia,2010-2012 Student Weight Status Category Repor...,2010-2012,NaN,NaN,Percentage overweight or obese (85th percentil...,g65,Percentage,37.1,35.4 - < 37.8 : Q3,Northeastern New York,NaN,700463.0
Columbia,2010-2012 Student Weight Status Category Repor...,2010-2012,NaN,NaN,Percentage overweight but not obese (85th-<95t...,g66,Percentage,15.9,0 - < 16.2 : Q1 & Q2,Northeastern New York,NaN,700463.0
Columbia,2010-2012 Student Weight Status Category Repor...,2010-2012,NaN,NaN,Percentage obese (95th percentile or higher ) ...,g67,Percentage,18.9,18.0 - < 19.4 : Q3,Northeastern New York,NaN,700463.0
Columbia,2010-2012 Student Weight Status Category Repor...,2010-2012,NaN,NaN,Percentage overweight or obese (85th percentil...,g68,Percentage,34.8,33.9 - < 36.5 : Q3,Northeastern New York,NaN,700463.0
Columbia,2010-2012 Student Weight Status Category Repor...,2010-2012,NaN,NaN,Percentage overweight but not obese (85th-<95t...,g69,Percentage,20.9,18.9 + : Q4,Northeastern New York,NaN,700463.0
Columbia,2010-2012 Student Weight Status Category Repor...,2010-2012,NaN,NaN,Percentage obese (95th percentile or higher ) ...,g70,Percentage,18.7,0 - < 21.1 : Q1 & Q2,Northeastern New York,NaN,700463.0
Columbia,2010-2012 Student Weight Status Category Repor...,2010-2012,NaN,NaN,Percentage overweight or obese (85th percentil...,g71,Percentage,39.6,37.5 - < 40.1 : Q3,Northeastern New York,NaN,700463.0
Columbia,2009-2011 NYS Pediatric Nutrition Surveillance...,2009-2011,540,Average annual population,Percentage obese (95th percentile or higher) c...,g72,Percentage,17.8,16.0 + : Q4,Northeastern New York,288,700463.0
Columbia,2009-2011 NYS Pediatric Nutrition Surveillance...,2009-2011,579,Average annual population,Percentage of children (aged 2-4 years) enroll...,g73,Percentage,80.7,75.2 - < 80.7 : Q2,Northeastern New York,1403,700463.0
Columbia,2008-2009 NYS Expanded Behavioral Risk Factor ...,2008-2009,NaN,NaN,Age-adjusted percentage of adults overweight o...,g74,Percentage,57.5,0 - < 62.9 : Q1 & Q2,Northeastern New York,NaN,700463.0
Columbia,2008-2009 NYS Expanded Behavioral Risk Factor ...,2008-2009,NaN,NaN,Age-adjusted percentage of adults obese (BMI 3...,g75,Percentage,22.4,0 - < 27.6 : Q1 & Q2,Northeastern New York,NaN,700463.0
Columbia,2008-2009 NYS Expanded Behavioral Risk Factor ...,2008-2009,NaN,NaN,Age-adjusted percentage of adults who did not ...,g76,Percentage,82.3,80.7 + : Q4,Northeastern New York,NaN,700463.0
Columbia,2008-2009 NYS Expanded Behavioral Risk Factor ...,2008-2009,NaN,NaN,Age-adjusted percentage of adults eating 5 or ...,g77,Percentage,26.8,26.0 + : Q3 & Q4,Northeastern New York,NaN,700463.0
Delaware,2010-2012 Student Weight Status Category Repor...,2010-2012,NaN,NaN,Percentage obese (95th percentile or higher) -...,g64,Percentage,22.2,20.4 + : Q4,Northeastern New York,NaN,353853.0

In [128]:
health_df.to_excel("NY Health and Income.xls")